FROM php:7.4-fpm

RUN apt-get update
RUN apt-get install -y libzip-dev
RUN docker-php-ext-install pdo_mysql zip

RUN curl -L 'https://getcomposer.org/download/latest-2.x/composer.phar' > /usr/local/bin/composer && chmod 755 /usr/local/bin/composer

COPY app-entrypoint.sh /usr/local/bin/docker-php-entrypoint

WORKDIR /srv/christmas-queue
